practicaFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teVeoapp.urls')),
]

teVeoapp/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('config/', views.config, name='config'),
    path('config/auth_link', views.generate_auth_link, name='auth_link'),
    path('config/set_session', views.set_session, name='set_session'),
    path('ayuda/', views.help, name='ayuda'),
    path('comentario/', views.comment_view, name='comment'),
    path('camaras/', views.mainCameras, name='mainCameras'),
    path('camaras/json', views.cameras_json, name='cameras_json'),
    path('camaras/<str:id>/', views.camera, name='camera'),
    path('camaras/<str:id>/json', views.camera_json, name='camera_json'),
    path('camaras/<str:id>/dyn', views.camera_dyn, name='camera_dyn'),
    path('camaras/<str:id>/img', views.latest_image, name='latest_image'),
    path(
        'camaras/<str:id>/comment',
        views.get_comments,
        name='get_comments'),
]

teVeoapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Camera(models.Model):
    # Fuente de datos que proviene
    source_id = models.CharField(max_length=100)
    # Id de la camara, conseguido en el XML, puede ser una cadena de texto o
    # un numero
    id = models.CharField(max_length=100, primary_key=True)
    # Primary_key es para que no se repitan las camaras,
    # ya que el id es único, si se repite, salta la excepción de IntegrityError
    # src es la dirección https de la camara a la cual le pedimos la imagen
    src = models.CharField(max_length=200)
    # Nombre de la camara
    name = models.CharField(max_length=100)
    # Coordenadas de la camara
    coordinates = models.CharField(max_length=100)
    # Directorio donde se guardan las imagenes
    img_path = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.source_id}{self.id} - {self.name}'


class Comment(models.Model):
    # Atributo que indica la persona que ha hecho el comentario
    name = models.CharField(max_length=100)
    # Comentario de la camara
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    # Comentario, con blanck=False, no se puede dejar vacio
    comment = models.CharField(max_length=200, blank=False)
    # Fecha del comentario, auto_now_add=True para que se añada la fecha
    # automáticamente
    date = models.DateTimeField(auto_now_add=True)
    # Imagen de la cámara en el momento del comentario
    img_path_comment = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.camera} - {self.name} - {self.comment} - {self.date}'


class Token(models.Model):
    # Atributo que indica el usuario
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Atributo que indica el token
    token = models.CharField(max_length=200)
    # Atributo que indica el tamaño de la fuente
    font_size = models.CharField(max_length=200, null=True)
    # Atributo que indica el color de la fuente
    font_family = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f'{self.user} - {self.token}'

teVeoapp/forms.py
# En forms.py
from django import forms  # Importas el módulo de formularios de Django

# Defines una clase para tu formulario que hereda de forms.Form


class ConfigForm(forms.Form):
    # Defines un campo de texto para el nombre de usuario.
    # El argumento label establece la etiqueta del campo
    # que se mostrará en el formulario.
    # max_length establece la longitud máxima
    # permitida para el texto ingresado.
    # required=False significa que este campo no es obligatorio.
    # Si el usuario no introduce nada, se enviará None.
    username = forms.CharField(
        label='Nombre de Usuario', max_length=100, required=False)

    # Defines un campo de selección para el tamaño de la fuente.
    # El argumento choices establece las opciones disponibles. Cada opción es
    # una tupla donde el primer elemento es el valor que se enviará si se
    # selecciona la opción, y el segundo elemento es la etiqueta de la opción
    # que se mostrará en el formulario.
    font_size = forms.ChoiceField(
        choices=[('large', 'Grande'),
                 ('standard', 'Estándar'),
                 ('small', 'Pequeña')])

    # Defines un campo de selección para la familia de fuentes, de manera
    # similar al campo font_size.
    font_family = forms.ChoiceField(choices=[
        ('Roboto', 'Roboto'),
        ('Arial', 'Arial'),
        ('Times New Roman', 'Times New Roman'),
        ('Verdana', 'Verdana'),
        ('Helvetica', 'Helvetica'),
        ('Courier New', 'Courier New'),
        ('C4 Type', 'C4 Type')
    ])

teVeoapp/views.py
from django.shortcuts import render, redirect
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    JsonResponse,
    Http404,
)
from .models import Camera, Comment, Token
from django.utils import timezone
from .manageMedia import *  # Importar todas las funciones de media_operations
from .manageUser import get_user_config
from .manageOrder import *  # Importar todas las funciones de manageOrder
import time
from .forms import ConfigForm
from urllib.parse import urlparse, parse_qs
from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.models import User
from django.urls import reverse
from django.core import serializers
from django.views.decorators.cache import never_cache

# Create your views here.

SELECTED_XML = "selected_xml"


def generate_auth_link(request):
    """
    Genera un enlace de autorización para la sesión actual.
    """
    auth_token = request.session.get('auth_token')
    if auth_token is None:
        # Si no hay un token de autenticación, crea uno
        user = User.objects.get(username=request.session['username'])
        token, created = Token.objects.get_or_create(user=user)
        if created:
            token.token = default_token_generator.make_token(user)
            token.font_size = request.session['font_size']
            token.font_family = request.session['font_family']
            token.save()
        auth_token = token.token
        request.session['auth_token'] = auth_token
    auth_link = request.build_absolute_uri(
        reverse('set_session')) + f'?auth_token={auth_token}'
    return JsonResponse({'auth_link': auth_link})


def set_session(request):
    """
    Establece la sesión actual en la sesión
    con el identificador de sesión en la URL.
    """
    if request.method == 'POST':
        auth_link = request.POST.get('auth_link')
        if auth_link is not None:
            url = urlparse(auth_link)
            auth_token = parse_qs(url.query).get('auth_token', [None])[0]
            if auth_token is not None:
                try:
                    token = Token.objects.get(token=auth_token)
                    request.session['username'] = token.user.username
                    request.session['font_size'] = token.font_size
                    request.session['font_family'] = token.font_family
                    print(f"Nombre de usuario: {token.user.username}")
                    print(f"Tamaño de fuente: {token.font_size}")
                    print(f"Familia de fuentes: {token.font_family}")

                except Token.DoesNotExist:
                    messages.error(
                        request, 'El enlace de autorización no es válido.')
    return redirect('index')


def config(request):
    if request.method == 'POST':
        form = ConfigForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            font_size = form.cleaned_data['font_size']
            font_family = form.cleaned_data['font_family']
            request.session['username'] = username
            request.session['font_size'] = font_size
            request.session['font_family'] = font_family
            user, created = User.objects.get_or_create(username=username)
            if user is not None:
                token, created = Token.objects.get_or_create(user=user)
                if created:
                    token.token = default_token_generator.make_token(user)
                token.font_size = font_size
                token.font_family = font_family
                token.save()
                request.session['auth_token'] = token.token
            return HttpResponseRedirect('/')
        else:
            print(form.errors)
    else:
        form = ConfigForm()

    username, font_size, font_family = get_user_config(request)

    context = {
        'form': form,
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
    }
    return render(request, 'config.html', context)


def index(request):
    # Manejo de la sesion del usuario
    username, font_size, font_family = get_user_config(request)

    # Odenar los comentario por tiempo
    order = 'desc'
    if request.method == 'POST':
        order = request.POST.get('order', 'desc')

    comments = order_cameras_by_time(order)

    # Crear el contexto
    context = {
        'comments': comments,
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
    }

    # Importante hacer con render y no con HttpResponse porque render es mas
    # seguro y maneja mejor los errores
    return render(request, 'index.html', context)


@never_cache
def mainCameras(request):
    # Obtener las fuentes de datos disponibles en static/xml
    random_img = None
    order = 'desc'
    if request.method == 'POST':
        xml_selected = request.POST.get(f'{SELECTED_XML}')
        order = request.POST.get('order', 'desc')
        if xml_selected == "clean":
            clear_all()
        elif xml_selected is not None:
            print(f"XML seleccionado: {xml_selected}")
            load_cameras_from_xml(xml_selected)
            get_img_of_cameras(xml_selected)

    cameras = order_cameras_by_comments(order)

    username, font_size, font_family = get_user_config(request)
    # print(f"Username en mainCameras: {username},
    # Font size: {font_size}, Font family: {font_family}")

    random_img = get_random_img()
    xml_files = get_xml_files()

    context = {
        'request': request,
        'xml_files': xml_files,
        'random_img': random_img,
        'cameras': cameras,
        'cameras_count': cameras.count(),
        'comments_count': Comment.objects.count(),
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
    }
    return render(request, 'mainCameras.html', context)


def camera(request, id):
    # Seleccionar la cámara con el identificador indicado. Si no existe, se
    # mostrará un mensaje de error. En caso contrario, se mostrará la imagen
    # de la cámara, y un enlace para volver al listado de cámaras.

    # Obtener la cámara con el id indicado
    camera = Camera.objects.filter(id=id).first()

    if camera is None:
        return HttpResponse("Cámara no encontrada")

    # Ordenar los comentarios por tiempo
    order = 'desc'
    if request.method == 'POST':
        order = request.POST.get('order', 'desc')

    # Obtener todos los comentarios de la camera ordenados por fecha
    comments = order_comments_by_time(
        Comment.objects.filter(camera=camera), order)

    # Obtener el nombre de usuario, tamaño de fuente y familia de fuentes
    username, font_size, font_family = get_user_config(request)

    context = {
        'request': request,
        'camera': camera,
        'comments': comments,
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
    }

    return render(request, 'camera.html', context)

# Funcion para guardar un comentario si se ha hecho un post request


def save_comment_if_post(request, camera, name):
    comment_text = request.POST.get('body')  # Cambiar 'cuerpo' a 'body'
    if comment_text:  # Verificar si comment_text no es vacío
        # Guardar el comentario en la base de datos con la camara, comentario,
        # fecha y la imagen de la cámara en ese momento
        img_comment = save_img_comment(camera.img_path)
        comment = Comment(name=name, camera=camera, comment=comment_text,
                          date=timezone.now(), img_path_comment=img_comment)
        comment.save()


def comment_view(request):
    camera_id = request.GET.get('camera_id')
    camera = Camera.objects.filter(id=camera_id).first()
    username, font_size, font_family = get_user_config(request)

    if camera is None:
        return HttpResponse("Cámara no encontrada")

    if request.method == 'POST':
        save_comment_if_post(request, camera, username)

    # Obtener todos los comentarios de la camera de más reciente a más
    # antiguo
    comments = Comment.objects.filter(camera=camera).order_by('-date')
    context = {
        'request': request,
        'comments': comments,
        'camera': camera,
        'now': timezone.now(),
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
    }
    return render(request, 'comment.html', context)


def camera_dyn(request, id):
    # Seleccionar la cámara con el identificador indicado. Si no existe, se
    # mostrará un mensaje de error. En caso contrario, se mostrará la imagen
    # de la cámara, y un enlace para volver al listado de cámaras.
    camera = Camera.objects.filter(id=id).first()
    username, font_size, font_family = get_user_config(request)

    if camera is None:
        return HttpResponse("Cámara no encontrada")

    camera.img_path = get_actual_img(id)
    print(f"Imagen actual: {camera.img_path}")

    if request.method == 'POST':
        save_comment_if_post(request, camera, username)

    # Obtener todos los comentarios de la camera de más reciente a más
    # antiguo
    comments = Comment.objects.filter(camera=camera).order_by('-date')
    context = {
        'request': request,
        'comments': comments,
        'camera': camera,
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
        'now': timezone.now(),
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
    }

teVeoapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TeVeo</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <link rel="icon" type="image/ico" href="{% static 'img/icon/favicon.ico' %}">
    <!-- Iconos de la camara y de comentarios sib de Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body class="{{ font_size }} {{ font_family }}">
    <header id="header">
        <div class="header-container">
            <img src="{% static 'img/resources/header.jpg' %}" class="img-fluid header" alt="...">
            <a href="{% url 'index' %}" class="header-title">
              TeVeo
              <span class="user-text">Usuario: {{ username }}</span>
            </a>
        </div>
    </header>

    <nav id="navbar" class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a href="/">
          <img src="{% static 'img/icon/favicon.png' %}" alt="TeVeo Logo" style="width: 50px; height: 50px;">
          </a>
          <a class="navbar-brand" href="{% url 'index' %}">TeVeo</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <!-- Esto es para ir a la pagina Principal -->
              {% if request.path != '/' %}
                <li class="nav-item">
                  <a class="nav-link active text-nav-activated" aria-current="page" href="{% url 'index' %}">Principal</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <span class="nav-link disabled text-nav-desactivated" aria-current="page">Principal</span>
                </li>
              {% endif %}
              
              <!-- Esto es para el texto que te lleva a todas las camaras  -->
              {% if request.path != '/camaras/' %}
                <li class="nav-item">
                  <a class="nav-link active text-nav-activated" href="{% url 'mainCameras' %}">Cámaras</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <span class="nav-link disabled text-nav-desactivated" aria-current="page">Cámaras</span>
                </li>
              {% endif %}

              {% if request.path != '/config/' %}
                <li class="nav-item">
                  <a class="nav-link active text-nav-activated" href="{% url 'config' %}">Configuración</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <span class="nav-link disabled text-nav-desactivated" aria-current="page">Configuración</span>
                </li>
              {% endif %}

              {% if request.path != '/ayuda/' %}
                <li class="nav-item">
                  <a class="nav-link active text-nav-activated" href="{% url 'ayuda' %}">Ayuda</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <span class="nav-link disabled text-nav-desactivated" aria-current="page">Ayuda</span>
                </li>
              {% endif %}

              {% if request.path != '/admin/' %}
                <li class="nav-item">
                    <a class="nav-link active" style="color: rebeccapurple" href="{% url 'admin:index' %}">Admin</a>
                </li>
              {% else %}
                <li class="nav-item">
                    <span class="nav-link disabled text-nav-desactivated" aria-current="page">Admin</span>
                </li>
              {% endif %}
              
              
            </ul>
            
          </div>
        </div>
    </nav>

    <main id="main-content">
        {% block body %}
        {% endblock %}
    </main>

    <div id="footer" class="container">
      <footer class="py-4 my-0 border-top fixed-bottom bg-dark text-white">
        <div class="row">
          <div class="col d-flex justify-content-center align-items-center">
            <i class="fas fa-camera fa-2x me-2"></i>
            <h5 class="mb-0">Número de cámaras: <span class="badge bg-dark">{{ cameras_count }}</span></h5>
          </div>
          <div class="col d-flex justify-content-center align-items-center">
            <i class="fas fa-comments fa-2x me-2"></i>
            <h5 class="mb-0">Número de comentarios: <span class="badge bg-dark">{{ comments_count }}</span></h5>
          </div>
        </div>
      </footer>
    </div>
    
    <div class="b-example-divider"></div>
    
</body>
</html>

teVeoapp/templates/camera_dyn.html
{% extends 'base.html' %}
{% load static %}
<!-- index.html -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>


{% block body %}
<script src="https://unpkg.com/htmx.org@1.9.12"></script>
<div id="main-content" class="row">
    <div id="camera-details" class="col-6 text-center">
        <div class="text-white custom-gray-bg" style="border-radius: 10px; padding: 20px; margin-top: 20px; margin-right: 20px; margin-left: 20px;">
            <h1 style="margin-top: 20px;">{{ camera.name }}</h1>
            <p>Coordenadas: {{ camera.coordinates }}</p>
            <p>ID: {{ camera.id }}</p>
            <a href="{% url 'camera' camera.id %}" class="link">Ver cámara</a>
            <p>Hora actual: {{ now }}</p>
        </div>
        <img src="{% static camera.img_path %}" class="img_size_camera" alt="" hx-get="{% url 'latest_image' camera.id %}?{{now}}" hx-trigger="every 30s" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' hx-swap="outerHTML">
    </div>
    <div id="comment-section" class="col-6">
        <div class="text-white custom-gray-bg" style="border-radius: 10px; padding: 20px; margin-top: 20px; margin-right: 20px; margin-left: 20px;">
            <h1 style="margin-top: 20px; text-align: center;">Sección de Comentarios</h1>
        </div>
        <form id="comment-form" action="" method="POST" class="form-group row" style="margin-top: 20px; margin-right: 20px; margin-left: 20px;">
            {% csrf_token %}
            <div class="col-9">
                <label for="commentBody">Introduce un comentario para esta página:</label>
                <input type="text" id="commentBody" name="body" class="form-control" placeholder="Escribe tu comentario aquí...">
            </div>
            <div class="col-3 d-flex align-items-end">
                <button type="submit" class="btn mt-3 custom-gray-bg text-white">Enviar comentario</button>
            </div>
        </form>
        <div id="comment-list" hx-get="{% url 'get_comments' camera.id %}?{{now}}" hx-trigger="every 30s" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' hx-swap="outerHTML" hx-boost="true">
            {% include 'get_comments.html' %}
        </div>
    </div>
</div>

{% endblock %}

teVeoapp/templates/image.html
<!-- camera_image.html -->
{% load static %}
{% load tz %}
{% now "U" as current_timestamp %}
<img id="camera-image" src="{% static camera.img_path %}?{{current_timestamp}}" class="img_size_camera" alt="" hx-get="{% url 'latest_image' camera.id %}?{{current_timestamp}}" hx-trigger="every 30s" hx-swap="outerHTML">

teVeoapp/templates/mainCameras.html
{% extends 'base.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">


{% block body %}
{% if xml_files %}
<div id="data-sources" class="container text-center">
    <div class="row tn-primary">
        <div id="data-source-list" class="col-6 bg-custom-col-color text-gray-custom text-white"> <!-- Aplicando la clase personalizada -->
            <h2 class="mb-4 p-3 bg-dark text-white rounded mt-4">Fuentes de datos disponibles</h2>
            <form id="xml-selection-form" method="post">
                {% csrf_token %}
                {% for xml_file in xml_files %}
                    <div class="mb-2">
                        <span style="font-size: larger;" class="mt-4 text-white">{{ forloop.counter }}. Fuente de datos: {{ xml_file }}</span><br>
                        <button type="submit" class="btn btn-dark" name="selected_xml" value="{{ xml_file }}">Cargar fuente de datos</button>
                    </div>
                    <hr>
                {% endfor %}
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark" name="selected_xml" value="clean">Limpiar datos (imágenes/comentarios)</button>
                </form>
                <a class="link" href="{% url 'cameras_json' %}">Cámaras en JSON</a>
            </form>
        </div>
        <div id="camera-list" class="col-6 bg-custom-col-color text-gray-custom"> <!-- Aplicando la clase personalizada -->
            <h2 class="mb-4 p-3 bg-dark text-white rounded mt-4">Lista de cámaras</h2>
            <div class="container text-center">
                <figure>
                    {%if random_img %}
                        <img src="{% static 'img/data/'|add:random_img %}" class="img-thumbnail" alt="" style="width: 300px; height: 200px;">
                        <figcaption class="text-white">Imagen aleatoria</figcaption>
                    {% else %}
                        <h2 class="mb-4 p-3 bg-danger rounded text-white">&#9888; No hay imagenes cargadas carga alguna fuente de datos  &#9888;</h2>
                    {% endif %}
                </figure>
                <hr>
                <div class="row">
                    {% if cameras %}
                        <div id="cameraCarousel" class="carousel slide" data-bs-ride="carousel">
                            <div class="carousel-inner">
                                {% for camera in cameras %}
                                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                        <div class="d-flex justify-content-center align-items-center">
                                            <img src="{% static camera.img_path %}" class="d-block w-100 img-fluid" alt="{{ camera.name }}" style="max-height: 300px;">
                                        </div>
                                        <div class="carousel-caption d-none d-md-block text-center">
                                            <h5 class="information">{{ camera.name }}</h5>
                                            <p class="information">ID: {{ camera.id }}</p>
                                            <div class="row">
                                                <a href="{% url 'camera' camera.id %}" class="link">Página de la cámara</a>
                                                <a href="{% url 'camera_dyn' camera.id %}" class="link">Página dinámica</a>
                                                <a href="{% url 'comment' %}?camera_id={{ camera.id }}" class="link">Página de comentarios, actualmente: {{ camera.comment_set.count }}</a>
                                                <a href="{% url 'camera_json' camera.id %}" class="link">JSON</a>
                                                
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#cameraCarousel" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#cameraCarousel" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                        <hr> 
                    {% endif %}
                
                    <div class="container">
                        <h2 class="mb-4 p-3 bg-dark text-white rounded mt-4">Lista de cámaras ordenadas</h2>
                        <form id="camera-order-form" method="post" style="margin-bottom: 2rem;"> <!-- Añadiendo margin-bottom -->
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="order" class="col-sm-4 col-form-label custom-label text-white">Ordenar cámaras por:</label>
                                <div class="col-sm-6">
                                    <select class="form-control" id="order" name="order">
                                        <option value="desc">Más a menos comentarios</option>
                                        <option value="asc">Menos a más comentarios</option>
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <button type="submit" class="btn btn-dark">Ordenar</button>
                                </div>
                            </div>
                        </form>
                        <div class="row justify-content-center">
                            {% for camera in cameras %}
                            <div class="col-md-12">
                                <div class="card mb-3">
                                    <div class="row g-0">
                                        <div class="col-md-8 d-flex align-items-center rounded custom-gray-bg">
                                            <div class="card-body text-center text-white">
                                                <h5 class="card-title">{{ camera.name }}</h5>
                                                <p class="card-text">
                                                    ID: {{ camera.id }} | Comentarios: {{ camera.comment_set.count }}
                                                </p>
                                                <div class="row">
                                                    <a href="{% url 'camera' camera.id %}" class="link">Página de la cámara</a>
                                                    <a href="{% url 'camera_dyn' camera.id %}" class="link">Página dinámica</a>
                                                    <a href="{% url 'comment' %}?camera_id={{ camera.id }}" class="link">Página de comentarios, actualmente: {{ camera.comment_set.count }}</a>
                                                    <a href="{% url 'camera_json' camera.id %}" class="link">JSON</a>
                                                    
                                                    
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Imagen de la cámara -->
                                        <div class="col-md-4 d-flex align-items-center">
                                            <img src="{% static camera.img_path %}" class="card-img-bottom mx-auto d-block" alt="{{ camera.name }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    
                    <!-- Añadir un margen por abajo para que el pie no tape la última cámara de la lista -->
                    <div class="mb-5"></div>

                </div>
            </div>
        </div>
    </div>
</div>

{% else %}
    <h1>¡No hay cámaras disponibles!</h1>
{% endif %}
{% endblock %}